name: Build firmware

on:
  push:
    branches:
      - philipstarkey/actions
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker compose build --pull

      - name: Run docker container
        run: docker compose up

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            build/prawnblaster/prawnblaster.uf2
            build/prawnblaster/prawnblasteroverclock.uf2